### ISSUE TITLE
Install fails during Chromium download

### ISSUE THREAD

**Issue by travisdowns** [shakiba/svgexport#77]
Installation of svgexport fails on my Ubuntu 19.10 system:

~~~
$ sudo npm install svgexport -g
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
/usr/local/bin/svgexport -> /usr/local/lib/node_modules/svgexport/bin/index.js

> puppeteer@2.1.1 install /usr/local/lib/node_modules/svgexport/node_modules/puppeteer
> node install.js

ERROR: Failed to download Chromium r722234! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/svgexport/node_modules/puppeteer/.local-chromium'
  -- ASYNC --
    at BrowserFetcher.<anonymous> (/usr/local/lib/node_modules/svgexport/node_modules/puppeteer/lib/helper.js:111:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/svgexport/node_modules/puppeteer/install.js:66:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path:
   '/usr/local/lib/node_modules/svgexport/node_modules/puppeteer/.local-chromium' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@2.1.1 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the puppeteer@2.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-28T22_10_38_983Z-debug.log
~~~

If I set `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` it succeeds.

**Comment by travisdowns** [comment]
Seems to be a puppeteer install issue:

https://github.com/puppeteer/puppeteer/issues/375

I worked around by using `--unsafe-perm=true` as suggested in [this comment](https://github.com/puppeteer/puppeteer/issues/375#issuecomment-363466257).

**Comment by agamm** [comment]
The latest version of `svgexport` isn't updated (0.4.0 currently) with the github source code. Try to install like so: `npm install shakiba/svgexport -g` 
@travisdowns
