### ISSUE TITLE
Installed on ubuntu server 2004 (on raspberry pi) cannot run

### ISSUE THREAD

**Issue by SilveryStar** [shakiba/svgexport#88]
- Environment
```
ubuntu@ubuntu:~$ uname -a
Linux ubuntu 5.4.0-1018-raspi #20-Ubuntu SMP Sun Sep 6 05:11:16 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
ubuntu@ubuntu:~$ npm -v
6.14.8
ubuntu@ubuntu:~$ node -v
v14.10.0
ubuntu@ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

When I use the command `svgexport test.svg test.jpg`, the following error occurs (the `test.svg` file has been guaranteed to exist)
```
(node:36573) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/usr/lib/node_modules/svgexport/node_modules/_puppeteer@3.3.0@puppeteer/.local-chromium/linux-756035/chrome-linux/chrome: 22: Syntax error: "(" unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/usr/lib/node_modules/svgexport/node_modules/_puppeteer@3.3.0@puppeteer/lib/launcher/BrowserRunner.js:159:20)
    at Interface.<anonymous> (/usr/lib/node_modules/svgexport/node_modules/_puppeteer@3.3.0@puppeteer/lib/launcher/BrowserRunner.js:149:65)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:424:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1308:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:36573) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:36573) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kryztoval** [comment]
You seem to be trying to run it in a server/headless rpi. This tool requires a browser/x11 installed in order to run it, render it and capture it. Can you check if you have X11 libraries installed?

I believe puppeteer installs chromium binaries and conector, just X11 is not included in the install
